### ISSUE TITLE
Úkol 1

### ISSUE THREAD

**Issue by Michaela-Vosvrdova** [Michaela-Vosvrdova/python-1-podzim-2022#1]
https://github.com/Michaela-Vosvrdova/python-1-podzim-2022/blob/main/ukol-01.py

Konečně úkol č. 1 :)

**Comment by AnetaPopelova** [comment]
👍 

P.S.:
Mozna bych zauvazovala o pojmenovani promenne `predan = input("Zadejte kód balíku: ")`. Bez kontextu bych predpokladala, ze promenna bude obsahovat informaci, zda byl balik predan. Je tam ale kod baliku k provereni. Jednoduche `kod_baliku` by bylo vystiznejsi. 

Kdyz pak budes mit promennych desitky nebo budes cist cizi kod, spravne pojmenovani ocenis ;-)

**Comment by Michaela-Vosvrdova** [comment]
Jo jo, máš úplnou pravdu, kdybych to četla u cizího, taky bych čekala boolean. Díky za upozornění. Jsem fakt ráda za tenhle váš support, člověk by na takový "důležitý blbosti" nepřišel nebo až za hodně dlouho a po hodně kiksech :D
